name: Generate Release Notes

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate changelog
        run: |
          echo "Generating changelog for $GITHUB_REF"
          git log -1 --pretty=format:"%h - %s (%an)" > release-notes.txt

      - name: Upload release notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release-notes.txt
